// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseTorrent(arg1) {
  return window['go']['ui']['UI']['ParseTorrent'](arg1);
}

export function RemoveTorrent(arg1) {
  return window['go']['ui']['UI']['RemoveTorrent'](arg1);
}
