defmodule Echo.Tracker.Types.AnnounceAttrs do
  @typedoc """
  Represents the attributes for tracker announce. The keys are:

  - `info_hash`: 20-byte SHA1 hash of the value of the `info` key from the
  metainfo file.
  - `peer_id`: 20-byte string used as a unique ID for the client, generated by
  the client at startup.
  - `port`: the port number that the client is listening on.
  - `uploaded`: the total number of bytes uploaded.
  - `downloaded`: the total number of bytes downloaded.
  - `left`: the number of bytes client still has to download.
  - `compact`: setting this to 1 indicates that the client accepts a compact
  response. The peers list is replaced by a peers string with 6 bytes per peer.
  The first four bytes are the host (in network byte order), the last two bytes
  are the port (network byte order). 
  - `no_peer_id`: indicates that the tracker can omit peer id field in peers
  dictionary. This option is ignored if compact is enabled.
  - `event`: if specified, must be one of `:started`, `:completed`, `:stopped`.
  If not specified, then this request is performed at regular internval.
  - `ip`: (optional) the true ip address of the client machine, in dotted quad
  format or ipv6 address.
  - `num_want`: (optional) number of peers that the client would like to
  receive from the tracker. Deafults to 50 peers.
  - `key`: (optional) additional identification that is not shared with any
  other peers. It is intended to allow a client to prove their identity should
  their IP address change.
  - `trackerid`: (optional) if a previous announce contained a tracker id, it
  should be set here.
  """
  @type t :: %{
          optional(:compact) => 0 | 1,
          optional(:ip) => String.t(),
          optional(:key) => String.t(),
          optional(:trackerid) => String.t(),
          optional(:numwant) => pos_integer(),
          peer_id: binary(),
          info_hash: binary(),
          port: pos_integer(),
          left: non_neg_integer(),
          uploaded: non_neg_integer(),
          downloaded: non_neg_integer(),
          event: :started | :completed | :stopped
        }
end

defmodule Echo.Tracker.Types.Peer do
  @moduledoc false

  @typedoc """
  Represents the peer info returned by the tracker.

  - `ip`: peer's IP address either IPv6 or IPv4 or DNS name
  - `port`: peer's port number
  - `peer_id`: (optional) peer's self selected ID
  """
  @type t :: %__MODULE__{
          port: pos_integer(),
          ip: String.t() | nil,
          peer_id: String.t() | nil
        }

  @enforce_keys [:ip, :port]
  defstruct(ip: nil, port: 0, peer_id: nil)
end

defmodule Echo.Tracker.Types.AnnounceResponse do
  @moduledoc false

  @typedoc """
  Represents the tracker announce response. It has the following fields:

  - `interval`: interval in seconds that the client should wait between sending
  regular requests to the tracker.
  - `min_interval`: (optional)  minimum announce interval.
  - `tracker_id`: a string that the client should send back on its next
  announcements.
  - `seeders`: number of peers with the complete file.
  - `leechers`: number of peers that are downloading the file.
  - `peers`: remote peer addresses
  """
  @type t :: %__MODULE__{
          interval: pos_integer(),
          seeders: non_neg_integer(),
          leechers: non_neg_integer(),
          tracker_id: String.t() | nil,
          min_interval: pos_integer() | nil,
          peers: [Echo.Tracker.Types.Peer.t()]
        }

  @enforce_keys [:interval, :peers, :seeders, :leechers]
  defstruct(interval: 0, peers: [], seeders: 0, leechers: 0, tracker_id: nil, min_interval: nil)
end
